// This should only be temporary 🤞 1/23/23

export const PublisherImages = {
  "First Round Review": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce47131cd996.png",
  "Wait But Why": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdc358b841c6.png",
  "Quartz": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5d532e02319f3.png",
  "Nautilus": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdc356543935.png",
  "New York Magazine": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce471d9b5185.png",
  "The Cut": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c22a77af6.png",
  "Science of Us": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c14966ec1.png",
  "Daily Intelligencer": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce478dbe33c4.png",
  "Fast Company": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c1e989ebd.png",
  "Harvard Business Review": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/6397ad4182eae.png",
  "Recode": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c0b3054df.png",
  "SB Nation": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c652ea471.png",
  "Eater": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/635adf7585116.png",
  "The Verge": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c763e1808.png",
  "Vox": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdc35fb67f18.png",
  "Buffer": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c1aff31fe.png",
  "Time Dorks": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdf1174e5af8.png",
  "The Atlantic": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dcc1c19e51ea.png",
  "The Marginalian (formerly Brain Pickings)": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/6189e3daee1ff.png",
  "Aeon": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdc364853ee0.png",
  "The Guardian": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd51115764.png",
  "Farnam Street": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5cdf0fa081e16.png",
  "Lifehacker": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5c9fa92221.png",
  "Outside": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/613009c5a76f9.png",
  "freeCodeCamp": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5bdadd4a19.png",
  "Kiplinger": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5ca607c9f7.png",
  "CityLab": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ef3c20a45f47.png",
  "Medium": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce5bf65c0308.png",
  "Popular Science": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60e4df2ca511d.png",
  "Saveur": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ce69f3324877.png",
  "Narratively": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/626b150294083.png",
  "Mental Floss": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd5fbeffa9.png",
  "Inc.": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e06729ce37ab.png",
  "Brad Stulberg": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/620ef9a9ca9fb.png",
  "Atlas Obscura": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e06677763ce2.png",
  "The Hedgehog Review": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5d361a21c15a6.png",
  "Texas Monthly": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e0673964e4b4.png",
  "MIT Technology Review": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd99f0658c.png",
  "Bloomberg Businessweek": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5db9f9be8df08.png",
  "Bloomberg": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5db9fb68b6b7f.png",
  "Scientific American": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5db9fc818a603.png",
  "BBC News": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dba05004ba90.png",
  "BBC Culture": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dd63aca0799b.png",
  "BBC Travel": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dd63cd246414.png",
  "BBC Future": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dd63d1c4af18.png",
  "BBC Worklife": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dd63d5fc2704.png",
  "Rolling Stone": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dea664ccbd84.png",
  "Variety": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5dea688cc19a0.png",
  "Nir Eyal": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5df954efb76d2.png",
  "Afar": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd56e9a7f6.png",
  "Slate": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e066b8997f67.png",
  "TED Ideas": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e067135be2f9.png",
  "The Washington Post": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e4f02a3d51ff.png",
  "The Conversation": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e41cf5d22a5a.png",
  "The Outline": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e41cfe7498ef.png",
  "NYLON": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e41d0c356f52.png",
  "Inverse": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd949562c0.png",
  "Foreign Policy": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5e7a836871a63.png",
  "Domino": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5ecfd69945da6.png",
  "The New York Review of Books": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5eaad2c8ba0ca.png",
  "90MIN": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5eced655682f4.png",
  "Smithsonian Magazine": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5f1b4ba46f5e9.png",
  "Apartment Therapy": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5f1b4d37b8b79.png",
  "The Kitchn": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5f1b4da381b0b.png",
  "Quanta Magazine": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5f64c9385ebd8.png",
  "Literary Hub": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5fac6a517783d.png",
  "Knowable Magazine": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/5fac6b1f8e7d8.png",
  "Natasha’s Kitchen": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/604bf5967e8c6.png",
  "Feel Good Foodie": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/604bf1a5afa23.png",
  "Well Plated": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/604bf18a1163c.png",
  "Damn Delicious": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/604bf10db1e8b.png",
  "The Home Edit": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/604bf62795223.png",
  "Esquire": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/606e2c35453e2.png",
  "Truly*Adventurous": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/606e326dd0987.png",
  "Delish": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c13e11e4335.png",
  "Bicycling": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c27d25aa1b1.png",
  "Car and Driver": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c27f95f2ad1.png",
  "Country Living": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c289b086fc0.png",
  "Women’s Health": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c286a8b5063.png",
  "Popular Mechanics": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c287a19c36e.png",
  "Men’s Health": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c28a1e4bad1.png",
  "Good Housekeeping": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c28a8969c29.png",
  "Elle": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c28afceb462.png",
  "Runner’s World": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c28c14b38b4.png",
  "Prevention": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60c28d029bdb9.png",
  "Field & Stream": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60e4e48f27575.png",
  "Outdoor Life": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/60e4e17a8d5a9.png",
  "Stylist": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/612e8c3f2caff.png",
  "Culture Study": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/61e86dec5b2ed.png",
  "MIT Press Reader": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/61ba712e29b3c.png",
  "MEL Magazine": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/623cf5e7102cf.png",
  "The Drive": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/623cf5b5b907f.png",
  "The War Zone": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/627aa4cf28f6d.png",
  "The Telegraph": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/62f2f4f3c4c8f.png",
  "Collectors Weekly": "https://pocket-syndicated-publisher-logos.s3.amazonaws.com/63a0a91e9c32f.png"
}
